CONFIG_LED_PERIOD_MS=500
CONFIG_PWM=y


CONFIG_THREAD_NAME=y           # For thread names
CONFIG_THREAD_STACK_INFO=y     # For thread information
CONFIG_INIT_STACKS=y           # For Stack Watermarks
CONFIG_THREAD_MONITOR=y        # For thread search
CONFIG_THREAD_RUNTIME_STATS=y  # For CPU usage tracking
