#ifndef SL_DEVICE_INIT_HFXO_CONFIG_H
#define SL_DEVICE_INIT_HFXO_CONFIG_H

#define SL_DEVICE_INIT_HFXO_MODE           cmuHfxoOscMode_Crystal
#define SL_DEVICE_INIT_HFXO_FREQ           38400000
#define SL_DEVICE_INIT_HFXO_CTUNE          120

#endif /* SL_DEVICE_INIT_HFXO_CONFIG_H */